name: ActionsTest

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -f docker/Dockerfile -t actions --no-cache .
        

    - name: Run the Docker image
      run: |
        docker run -i actions:latest
