name: ActionsTest

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & run the Docker image
      run: |
        docker build -f docker/Dockerfile -t actions --no-cache .
        docker run -it --rm actions:latest

