name: ActionsTest

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build --build-arg test=${{ secrets.TEST }} -t actions --no-cache .
        

    - name: Run the Docker image
      run: |
        docker run -i -e "TEST2=${{ secrets.TEST2 }}" actions:latest
